exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
highlighter: pygments

title : Reclaiming Civics
image:
  feature: shutterstock_465700832.jpg
description: Replacing political argument with political dialogue for more respectful, effective communication
owner :
  name: Reclaiming Civics
  email: dan@reclaimingcivics.org
  github: ReclaimingCivics
  reddit: ReclaimingCivics
  twitter: ReclaiminrCivics

markdown: redcarpet
redcarpet:
  extensions: ["strikethrough"]

JB :
  version : 0.3.0
  BASE_PATH : false
  ASSET_PATH : false
  archive_path: /archive.html
  categories_path : /categories.html
  tags_path : /tags.html
  atom_path : /atom.xml
  rss_path : /rss.xml
  comments :
    provider : disqus
    disqus :
      short_name : jekyllbootstrap
    livefyre :
      site_id : 123
    intensedebate :
      account : 123abc
    facebook :
      appid : 123
      num_posts: 5
      width: 580
      colorscheme: light
  analytics :
    provider : google 
    google : 
        tracking_id : 'UA-123-12'
    getclicky :
      site_id : 
    mixpanel :
        token : '_MIXPANEL_TOKEN_'

  sharing :
    provider : false

